[package]
name = "bevyjam3"
version = "0.1.0"
edition = "2021"
default-run = "bevyjam3"

[dependencies]
bevy = "0.10.1"
bevy-inspector-egui = "0.18.3"
bevy_ecs_ldtk = { version = "0.6.0", features = ["atlas"] }
bevy_ecs_tilemap = "0.10.0"
bevy_rapier2d = "0.21.0"
clap = "4.2.1"
serde = "1.0.159"
serde_json = "1.0.95"

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3
