[build]
# Setting public_url here breaks trunk serve
# so instead use trunk build --public-url "./" instead until fixed
# https://github.com/thedodd/trunk/issues/395
# public_url = "./"
filehash = false

[tools]
sass = "1.54.9" # Fixes ruby-sass being used instead of dart-sass
