name: "CI"
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jetli/trunk-action@v0.4.0
      - uses: Swatinem/rust-cache@v2
      - run: trunk build --release
      - uses: actions/upload-artifact@v2
        with:
          name: web
          path: dist

  deploy:
    name: Deploy
    if: github.ref == 'refs/heads/main' && github.repository_owner == 'kuviman'
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: web
